import Head from 'next/head';
import { getData } from '../mongodb/dbFunctions';
import Image from 'next/image';
import styled, { css } from 'styled-components';
const shadow = css`
  -webkit-box-shadow: 8px 8px 24px 0px rgba(24, 24, 24, 1);
  -moz-box-shadow: 8px 8px 24px 0px rgba(24, 24, 24, 1);
  box-shadow: 8px 8px 24px 0px rgba(24, 24, 24, 1);
`;

const Wrapper = styled.div`
  color: #2e2f35;
  padding: 20px;
  font-family: 'Montserrat', sans-serif;
`;

const Item = styled.div`
  background: #2e2f35;
  color: white;
  border-radius: 10px;
  padding: 30px;
  margin: 20px;
  display: inline-block;
  width: 400px;
  display: flex;
  flex-direction: column;
  align-items: center;
  ${shadow}
`;
const ImageWrapper = styled.div`
  border-radius: 10px;
  overflow: hidden;
  position: relative;
  width: 300px;
  height: 200px;
  background: white;
  display: flex;
  justify-content: center;
  align-items: center;
  img {
    max-width: 300px;
    max-height: 200px;
  }
  ${shadow}
  transition: all, cubic-bezier(0.075, 0.82, 0.165, 1), 0.3s;
  &:hover {
    transform: scale(1.1);
  }
`;

const Column = styled.div`
  display: flex;
  flex-direction: column;
`;
const Title = styled.div`
  margin: 20px;
  padding: 10px;
  border-radius: 10px;
  ${shadow}
`;
const Price = styled.div`
  font-weight: 600;
  padding: 10px;
  border-radius: 10px;
  ${shadow}
`;

export default function Home({ date, items2 }) {
  const itemsList2 = items2.map(array => (
    <p key={'lol'}>
      array.map(item => <p key={item.itemTitle}>{item.itemTitle}</p>);
    </p>
  ));
  console.log('itemsList2', itemsList2);

  const date2 = new Date(date);
  console.log('items2', items2);
  const items = items2[0][0].data;
  console.log('items', items);
  // <Head>
  //   <title>Create Ceneo Bot App</title>
  //   <meta name="description" content="Generated by create next app" />
  //   <link rel="icon" href="/favicon.ico" />
  // </Head>;

  if (items?.length > 0) {
    const itemsList = items.map(item => (
      <Item key={item.itemTitle}>
        <a href={item.itemLink} target="blank">
          <ImageWrapper>
            <Image
              src={item.itemImage.url}
              alt={item.itemTitle}
              quality={100}
              width={item.itemImage.width}
              height={item.itemImage.height}
            ></Image>
          </ImageWrapper>
        </a>

        <Title>{item.itemTitle}</Title>
        <Price>{item.itemPrice}zł</Price>
      </Item>
    ));
    console.log('itemsList', itemsList);
    // console.log('itemsList', itemsList);
    return (
      <Wrapper>
        <h1 style={{ textAlign: 'center' }}>
          Data scraped at {date2.toLocaleString('pl-PL')}
        </h1>
        <Column>{itemsList}</Column>
        <Column>{itemsList2}</Column>
      </Wrapper>
    );
  } else {
    return <div>Couldn&#39;t connect to database.</div>;
  }
}

export async function getServerSideProps() {
  try {
    const data = await getData();
    console.log('data:', data);
    const items = data;
    // const date = data[0].date;
    const date = '2022-10-21T13:56:25.934Z';

    return {
      props: { items2: items, date },
    };
  } catch (err) {
    console.log('error', err);
    return { props: { connection: 'false' } };
  }
}
